<a href="https://colab.research.google.com/github/mahdiskj/DecisionTree_RandomForest/blob/main/random_forest_regression_GITHUB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Decision Tree Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('loan_data.csv')
X = dataset.iloc[:, 2:].values
y = dataset.iloc[:, 0:1].values

In [ ]:
print(y)

[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


In [ ]:
# SimpleImputer is a class of the sklearn.impute module
from sklearn.impute import SimpleImputer
# replacinf missing values (nan or empty values) with the mean of all the data :
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# fit method connects the Imputer object with the matrix of X 
imputer.fit(X)
#trasnform will apply the method 'fit' on X (non number values should be excluded)
X = imputer.transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
# random_state = 1 : to have the same result of the split every time the code is executed
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
# StandardScaler : the class for standadization
from sklearn.preprocessing import StandardScaler
# creating the standardization object:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 0.62  0.52  1.44 ... -0.3  -0.23 -0.43]
 [ 1.04  1.81  0.57 ... -0.3  -0.23 -0.43]
 [-1.36 -0.01  0.49 ... -0.3  -0.23 -0.43]
 ...
 [ 0.13  0.4  -0.17 ... -0.3   3.51 -0.43]
 [ 1.26  1.5   0.25 ... -0.3  -0.23 -0.43]
 [-0.85 -1.08 -1.31 ... -0.3  -0.23 -0.43]]


## Training the Decision Tree Regression model on the whole dataset

In [ ]:
from sklearn import tree
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# 'n_estimators' : the number of decision trees in the random forest; it can be tuned by trial and error
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train, y_train)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

[[0.   0.  ]
 [1.   1.  ]
 [0.95 1.  ]
 ...
 [0.01 0.  ]
 [0.   0.  ]
 [1.   1.  ]]


0.9724546047018212